#!/usr/bin/env bash
# Generate the local copy editor for a concept page.
#
#   ./concepts/edit.sh 08
#
#   concepts/08-open.html   the source
#   concepts/08-edit.html   generated, local only, NEVER published
#
# Open concepts/08-edit.html directly off disk (file://) or serve it:
#   python3 -m http.server 8123   →   localhost:8123/concepts/08-edit.html
#
# Edit text in place, then "Download" (Chrome blocks the clipboard on file://),
# and cut the next version from what came back:
#   python3 concepts/apply-copy.py ~/Downloads/copy-patch.json --from 08 --to 09
set -euo pipefail
cd "$(dirname "$0")"

V="${1:?usage: edit.sh <version>   e.g. edit.sh 08}"
[ -f "$V-open.html" ] || { echo "no such page: concepts/$V-open.html" >&2; exit 1; }

python3 - "$V" <<'PY'
import sys
v = sys.argv[1]
s = open(v + '-open.html').read()
s = s.replace('</head>',
  '<link rel="stylesheet" href="copy-editor.css">\n</head>', 1)
s = s.replace('</body>',
  '<script src="copy-editor.js"></script>\n</body>', 1)
s = s.replace('<title>', '<title>EDIT &middot; ', 1)
banner = ('<!-- GENERATED by concepts/edit.sh from %s-open.html.\n'
          '     Local editing copy. Do not hand-edit, do not publish. -->\n' % v)
open(v + '-edit.html', 'w').write(banner + s)
print('wrote concepts/%s-edit.html' % v)
PY
